name: CI
on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7

    - name: system version
      run: |
        uname -a

    - name: setup cl
      uses: 40ants/setup-lisp@76212e4597c780ad0e2ead24144b54310dffb6e3 #4.2.1
#      with:
#        asdf-system: ci-test

    - name: run lisp
      continue-on-error: true
      run: |
        echo 1
        echo "path=$PATH"
        ros -e '(format t "~a:~a on ~a~%...~%~%" (lisp-implementation-type) (lisp-implementation-version) (machine-type))'
        echo 3
        ros -e '(format t " fixnum bits:~a~%" (integer-length most-positive-fixnum))'
        ros -e "(format t \"tf = ~s~%\" (ql:where-is-system 'trivial-features))"
        ros -e '(format t "init features = ~s~%" *features*)'
        ros -e "(ql:quickload 'trivial-features)" -e '(format t "features = ~s~%" *features*)'

    - name: clear fasl cache
      run: |
        rm -rf ~/.cache/common-lisp/
        mkdir -p ~/.cache/common-lisp/

    - name: load code from clean fasl cache
      uses: 40ants/run-tests@663e2dc4907e1c46a3aa21a2e1cf7562e0a4db9d # 2.3.0
      with:
        asdf-system: 3bmd

    - name: load from fasls
      uses: 40ants/run-tests@663e2dc4907e1c46a3aa21a2e1cf7562e0a4db9d # 2.3.0
      with:
        asdf-system: 3bmd

    - name: test youtube extension
      uses: 40ants/run-tests@663e2dc4907e1c46a3aa21a2e1cf7562e0a4db9d # 2.3.0
      with:
        asdf-system: 3bmd-youtube

    - name: test table extension
      uses: 40ants/run-tests@663e2dc4907e1c46a3aa21a2e1cf7562e0a4db9d # 2.3.0
      with:
        asdf-system: 3bmd-ext-tables

    - name: test wiki links extension
      uses: 40ants/run-tests@663e2dc4907e1c46a3aa21a2e1cf7562e0a4db9d # 2.3.0
      with:
        asdf-system: 3bmd-ext-wiki-links

    - name: test definition-list extension
      uses: 40ants/run-tests@663e2dc4907e1c46a3aa21a2e1cf7562e0a4db9d # 2.3.0
      with:
        asdf-system: 3bmd-ext-definition-lists

    - name: test code-blocks extension
      uses: 40ants/run-tests@663e2dc4907e1c46a3aa21a2e1cf7562e0a4db9d # 2.3.0
      with:
        asdf-system: 3bmd-ext-code-blocks
